In [10]:
import numpy as np
import torch
import torch.nn as nn
from nnSampleVerification import sdfs, verifMethods, plotter

In [15]:
# Define the parameters of the distribution
num_samples = 100
num_dimensions = 4

# Sample from the multivariate Cauchy distribution
samples = np.random.standard_cauchy((num_samples, num_dimensions))

# Print the samples
print(samples)
# Calculate the correlation matrix
corr_matrix = np.array([[1.0, 0.1], [0.1, 1.0]])
# Generate samples from a standard Cauchy distribution
samples = np.random.standard_cauchy((num_samples, num_dimensions))
# Apply the linear transformation to correlate the input dimensions
correlated_samples = np.dot(samples, np.linalg.cholesky(corr_matrix).T)


class ReLUFeedforwardNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(ReLUFeedforwardNetwork, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

# Define the dimensions of the network
input_size = num_dimensions
hidden_size = 10
output_size = 2

# Create an instance of the ReLU feedforward network
network = ReLUFeedforwardNetwork(input_size, hidden_size, output_size)

# Print the network architecture
print(network)



[[ 3.92524420e+00 -1.60076797e-02 -6.36350350e-01  1.44482767e+01]
 [ 3.39534086e+00  1.37673363e+00 -2.17494778e-01  3.05961806e+00]
 [-6.94215170e-01 -1.50537666e+00  3.63283617e+01  9.27470709e-01]
 [-4.16247725e+00 -3.98741733e-01 -6.70898650e+00  2.04445115e+00]
 [-3.30163884e-01 -6.35077467e+01 -4.48207948e-01 -2.17051810e+01]
 [ 3.61702495e-01  1.66466039e+00 -2.08365694e+01  1.52220358e+00]
 [ 1.60869578e+01 -6.71673399e-02  1.31309215e+00 -1.73490354e-01]
 [ 1.24530571e-02  7.03388421e-01 -2.37914392e-01 -1.71513761e+00]
 [-3.46192316e+01 -4.90612632e-01  7.70181822e-01 -1.42799776e+00]
 [ 1.04813684e+00  1.21943825e+00  3.10292577e-01  7.21948687e-01]
 [-4.77546797e-01 -2.72140040e+00  2.23486936e-01 -3.87172725e+00]
 [ 3.59746058e-01  1.15987759e+00 -4.60335073e-01  2.00658286e+00]
 [-2.39424657e+00  7.90659925e-02 -5.65786969e-01  5.32066963e+00]
 [ 1.76749794e+00  4.06668188e-01  1.60110744e+00 -1.83331853e+01]
 [ 5.94997827e+00 -1.30492375e+00  4.76919176e-02  3.01534830e

ValueError: shapes (100,4) and (2,2) not aligned: 4 (dim 1) != 2 (dim 0)